# Generated by Django 6.0.3 on 2026-03-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.AutoField(db_column='estado_reserva_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de reserva',
                'verbose_name_plural': 'Estados de reserva',
                'db_table': 'estado_reserva',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(db_column='reserva_id', primary_key=True, serialize=False)),
                ('reservation_code', models.CharField(max_length=100, verbose_name='codigo_reserva')),
                ('periods_quantity', models.IntegerField(verbose_name='cantidad_periodos')),
                ('start_date', models.DateTimeField(verbose_name='fecha_inicio')),
                ('end_date', models.DateTimeField(verbose_name='fecha_fin')),
                ('pickup_location', models.CharField(max_length=255, verbose_name='ubicacion_recogida')),
                ('return_location', models.CharField(max_length=255, verbose_name='ubicacion_entrega')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor_total')),
                ('reservation_date', models.DateTimeField(verbose_name='fecha_reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(db_column='metodo_pago_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='payments.paymentmethod')),
                ('period_type', models.ForeignKey(db_column='tipo_periodo_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='publications.periodtype')),
                ('publication', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='publications.publication')),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.user')),
                ('status', models.ForeignKey(db_column='estado_reserva_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.reservationstatus')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
    ]
