name: flexidrive
description: FlexiDrive - Movilidad a tu ritmo

publish_to: 'none'

version: 2.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  google_fonts: ^8.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icons/icono.png"
  adaptive_icon_background: "#6B5BCD"
  adaptive_icon_foreground: "icons/icono.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/imagenes_carros/
    - assets/data/
    - assets/data/accounts/
    - assets/data/catalogs/
    - assets/data/operations/
    - assets/data/payments/
    - assets/data/security/
