name: flexidrive
description: FlexiDrive - Movilidad a tu ritmo

publish_to: 'none'

version: 2.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
<<<<<<< HEAD
  google_fonts: ^6.1.0
=======
  google_fonts: ^6.2.1
>>>>>>> 6c6effafc814e41565bf5324943d8b73133d554f

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/imagenes_carros/
