# Generated by Django 6.0.3 on 2026-03-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.AutoField(db_column='categoria_notificacion_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de notificacion',
                'verbose_name_plural': 'Categorias de notificacion',
                'db_table': 'categoria_notificacion',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(db_column='notificacion_id', primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255, verbose_name='asunto')),
                ('description', models.CharField(max_length=255, verbose_name='descripcion')),
                ('status', models.CharField(choices=[('no_leida', 'No leida'), ('leida', 'Leida')], default='no_leida', max_length=20, verbose_name='estado')),
                ('sent_at', models.DateTimeField(verbose_name='fecha_envio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.user')),
                ('category', models.ForeignKey(db_column='categoria_notificacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationcategory')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
            },
        ),
    ]
