# Generated by Django 6.0.3 on 2026-03-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.CharField(max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('was_successful', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Intento de inicio de sesion',
                'verbose_name_plural': 'Intentos de inicio de sesion',
                'db_table': 'login_attempt',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(db_column='sesion_usuario_id', primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=255, verbose_name='dispositivo')),
                ('operating_system', models.CharField(max_length=120, verbose_name='sistema_operativo')),
                ('ip_address', models.CharField(max_length=64, verbose_name='direccion_ip')),
                ('start_date', models.DateTimeField(verbose_name='fecha_inicio')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Sesion de usuario',
                'verbose_name_plural': 'Sesiones de usuario',
                'db_table': 'sesion_usuario',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=512)),
                ('is_revoked', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='accounts.user')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='security.usersession')),
            ],
            options={
                'verbose_name': 'Refresh token',
                'verbose_name_plural': 'Refresh tokens',
                'db_table': 'refresh_token',
            },
        ),
    ]
