# Generated by Django 6.0.3 on 2026-03-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id', models.AutoField(db_column='tipo_identificacion_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de identificacion',
                'verbose_name_plural': 'Tipos de identificacion',
                'db_table': 'tipo_identificacion',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(db_column='tipo_usuario_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de usuario',
                'verbose_name_plural': 'Tipos de usuario',
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='usuario_id', primary_key=True, serialize=False)),
                ('identification_number', models.CharField(max_length=50, verbose_name='numero_identificacion')),
                ('full_name', models.CharField(max_length=180, verbose_name='nombre_completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('phone', models.CharField(max_length=40, verbose_name='telefono')),
                ('password_hash', models.CharField(max_length=255, verbose_name='contrasena_hash')),
                ('can_publish', models.BooleanField(default=False, verbose_name='puede_publicar')),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='profiles/photos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_provider', models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=20)),
                ('provider_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identification_type', models.ForeignKey(db_column='tipo_identificacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.identificationtype')),
                ('user_type', models.ForeignKey(db_column='tipo_usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.usertype')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(db_column='preferencia_usuario_id', primary_key=True, serialize=False)),
                ('dark_mode', models.BooleanField(default=False, verbose_name='modo_oscuro')),
                ('language', models.CharField(max_length=20, verbose_name='idioma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Preferencia de usuario',
                'verbose_name_plural': 'Preferencias de usuario',
                'db_table': 'preferencia_usuario',
            },
        ),
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.AutoField(db_column='seguridad_usuario_id', primary_key=True, serialize=False)),
                ('two_factor_verification', models.BooleanField(default=False, verbose_name='verificacion_dos_pasos')),
                ('biometric_access', models.BooleanField(default=False, verbose_name='acceso_biometrico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='security_profiles', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Seguridad de usuario',
                'verbose_name_plural': 'Seguridad de usuarios',
                'db_table': 'seguridad_usuario',
            },
        ),
    ]
