# Generated by Django 6.0.3 on 2026-03-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodType',
            fields=[
                ('id', models.AutoField(db_column='tipo_periodo_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de periodo',
                'verbose_name_plural': 'Tipos de periodo',
                'db_table': 'tipo_periodo',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(db_column='publicacion_id', primary_key=True, serialize=False)),
                ('publication_date', models.DateTimeField(verbose_name='fecha_publicacion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='accounts.user')),
                ('vehicle', models.ForeignKey(db_column='vehiculo_id', on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Publicacion',
                'verbose_name_plural': 'Publicaciones',
                'db_table': 'publicacion',
            },
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.AutoField(db_column='imagen_publicacion_id', primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='publications/images/', verbose_name='url_imagen')),
                ('order', models.IntegerField(verbose_name='orden')),
                ('is_main', models.BooleanField(default=False, verbose_name='es_principal')),
                ('uploaded_at', models.DateTimeField(verbose_name='fecha_subida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publications.publication')),
            ],
            options={
                'verbose_name': 'Imagen de publicacion',
                'verbose_name_plural': 'Imagenes de publicacion',
                'db_table': 'imagen_publicacion',
            },
        ),
        migrations.CreateModel(
            name='PublicationPrice',
            fields=[
                ('id', models.AutoField(db_column='precio_publicacion_id', primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_type', models.ForeignKey(db_column='tipo_periodo_id', on_delete=django.db.models.deletion.CASCADE, related_name='publication_prices', to='publications.periodtype')),
                ('publication', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='publications.publication')),
            ],
            options={
                'verbose_name': 'Precio de publicacion',
                'verbose_name_plural': 'Precios de publicacion',
                'db_table': 'precio_publicacion',
            },
        ),
    ]
