# Generated by Django 6.0.3 on 2026-03-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.AutoField(db_column='categoria_vehiculo_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de vehiculo',
                'verbose_name_plural': 'Categorias de vehiculo',
                'db_table': 'categoria_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(db_column='vehiculo_id', primary_key=True, serialize=False)),
                ('line', models.CharField(max_length=120, verbose_name='linea')),
                ('model_year', models.IntegerField(verbose_name='modelo')),
                ('color', models.CharField(max_length=60, verbose_name='color')),
                ('seats', models.IntegerField(verbose_name='asientos')),
                ('transmission_type', models.CharField(max_length=60, verbose_name='tipo_transmision')),
                ('air_conditioning', models.BooleanField(default=False, verbose_name='aire_acondicionado')),
                ('fuel_type', models.CharField(max_length=60, verbose_name='tipo_combustible')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_column='categoria_vehiculo_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.vehiclecategory')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'vehiculo',
            },
        ),
    ]
