# Generated by Django 6.0.3 on 2026-03-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerificationStatus',
            fields=[
                ('id', models.AutoField(db_column='estado_verificacion_documento_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de verificacion de documento',
                'verbose_name_plural': 'Estados de verificacion de documento',
                'db_table': 'estado_verificacion_documento',
            },
        ),
        migrations.CreateModel(
            name='OwnerDocumentType',
            fields=[
                ('id', models.AutoField(db_column='tipo_documento_arrendador_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento de arrendador',
                'verbose_name_plural': 'Tipos de documento de arrendador',
                'db_table': 'tipo_documento_arrendador',
            },
        ),
        migrations.CreateModel(
            name='OwnerDocument',
            fields=[
                ('id', models.AutoField(db_column='documento_arrendador_id', primary_key=True, serialize=False)),
                ('document_file', models.FileField(upload_to='documents/owners/', verbose_name='url_documento')),
                ('upload_date', models.DateTimeField(verbose_name='fecha_subida')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha_verificacion')),
                ('observations', models.CharField(blank=True, max_length=255, null=True, verbose_name='observaciones')),
                ('file_size', models.IntegerField(default=0)),
                ('file_type', models.CharField(max_length=100)),
                ('verification_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_owner_documents', to='accounts.user')),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='owner_documents', to='accounts.user')),
                ('verification_status', models.ForeignKey(db_column='estado_verificacion_documento_id', on_delete=django.db.models.deletion.CASCADE, related_name='owner_documents', to='documents.documentverificationstatus')),
                ('verified_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_owner_documents', to='accounts.user')),
                ('owner_document_type', models.ForeignKey(db_column='tipo_documento_arrendador_id', on_delete=django.db.models.deletion.CASCADE, related_name='owner_documents', to='documents.ownerdocumenttype')),
            ],
            options={
                'verbose_name': 'Documento de arrendador',
                'verbose_name_plural': 'Documentos de arrendador',
                'db_table': 'documento_arrendador',
            },
        ),
    ]
