# Generated by Django 6.0.3 on 2026-03-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(db_column='opinion_id', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(verbose_name='calificacion')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opinion',
                'verbose_name_plural': 'Opiniones',
                'db_table': 'opinion',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(db_column='resena_id', primary_key=True, serialize=False)),
                ('review_date', models.DateTimeField(verbose_name='fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opinion', models.ForeignKey(db_column='opinion_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.opinion')),
                ('publication', models.ForeignKey(db_column='publicacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='publications.publication')),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Resena',
                'verbose_name_plural': 'Resenas',
                'db_table': 'resena',
            },
        ),
    ]
