# Generated by Django 6.0.3 on 2026-05-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_at',
        ),
    ]
