# Generated by Django 6.0.3 on 2026-05-13 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_unique_together_remove_city_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
