# Generated by Django 6.0.3 on 2026-03-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(db_column='banco_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'banco',
            },
        ),
        migrations.CreateModel(
            name='CardBrand',
            fields=[
                ('id', models.AutoField(db_column='marca_tarjeta_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca de tarjeta',
                'verbose_name_plural': 'Marcas de tarjeta',
                'db_table': 'marca_tarjeta',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodType',
            fields=[
                ('id', models.AutoField(db_column='tipo_metodo_pago_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de metodo de pago',
                'verbose_name_plural': 'Tipos de metodo de pago',
                'db_table': 'tipo_metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(db_column='tipo_persona_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de persona',
                'verbose_name_plural': 'Tipos de persona',
                'db_table': 'tipo_persona',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(db_column='metodo_pago_id', primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=False, verbose_name='predeterminado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.user')),
                ('payment_method_type', models.ForeignKey(db_column='tipo_metodo_pago_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='payments.paymentmethodtype')),
            ],
            options={
                'verbose_name': 'Metodo de pago',
                'verbose_name_plural': 'Metodos de pago',
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(db_column='tarjeta_id', primary_key=True, serialize=False)),
                ('last4', models.CharField(max_length=4, verbose_name='ultimos_4_digitos')),
                ('tokenized_card_reference', models.CharField(max_length=255, verbose_name='referencia_tokenizada')),
                ('expiration_month', models.IntegerField(verbose_name='mes_expiracion')),
                ('expiration_year', models.IntegerField(verbose_name='ano_expiracion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_brand', models.ForeignKey(db_column='marca_tarjeta_id', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='payments.cardbrand')),
                ('payment_method', models.ForeignKey(db_column='metodo_pago_id', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'tarjeta',
            },
        ),
        migrations.CreateModel(
            name='PSE',
            fields=[
                ('id', models.AutoField(db_column='pse_id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(db_column='banco_id', on_delete=django.db.models.deletion.CASCADE, related_name='pse_accounts', to='payments.bank')),
                ('payment_method', models.ForeignKey(db_column='metodo_pago_id', on_delete=django.db.models.deletion.CASCADE, related_name='pse_accounts', to='payments.paymentmethod')),
                ('person_type', models.ForeignKey(db_column='tipo_persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='pse_accounts', to='payments.persontype')),
            ],
            options={
                'verbose_name': 'Cuenta PSE',
                'verbose_name_plural': 'Cuentas PSE',
                'db_table': 'pse',
            },
        ),
    ]
